device: cuda
batch_size: 32

# Paths (relative to your user home directory)
data_dir: F:\JupyterWork\Testing GAN\Coding of GAN\Datasetv3
model_dir: F:\JupyterWork\Testing GAN\Coding of GAN\ModelAEV4
output_folder: F:\JupyterWork\Testing GAN\Coding of GAN\OutputAEV4

dataset: gcode_layers_V4.npy

save_results: true
load_ae: false

# AE settings
latent_size: 512
ae_epoch: 2001
